In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy.stats import zscore
import math

df = pd.read_csv('thiTHPT2018.csv')

C:\Users\Thuong\AppData\Local\Temp\ipykernel_7064\975336808.py:8: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('thiTHPT2018.csv')

In [2]:
df.drop('Unnamed: 1',axis=1 ,inplace=True)
df

,0,SoBD,Toan,Van,Anh,Ly,Hoa,Sinh,Su,Dia,GDCD,Unnamed: 10,KhoiA,KhoiB,KhoiC,KhoiD,KhoiA1,Ma Tinh,Ten Tinh,Vung mien
0,1,1,3.0,3.75,3.0,NaN,NaN,NaN,3.0,6.50,8.25,NaN,NaN,NaN,13.25,9.75,NaN,18,Bac Giang,Mien Bac
1,2,2,8.8,7.50,9.0,NaN,NaN,NaN,6.0,9.00,8.25,NaN,NaN,NaN,22.50,25.3,NaN,18,Bac Giang,Mien Bac
2,3,3,6.0,5.50,4.0,5.75,5.50,5.00,NaN,NaN,NaN,NaN,17.25,16.50,NaN,15.5,15.75,18,Bac Giang,Mien Bac
3,4,4,3.4,5.75,2.6,NaN,NaN,NaN,3.5,4.75,7.25,NaN,NaN,NaN,14.00,11.75,NaN,18,Bac Giang,Mien Bac
4,5,5,3.8,6.75,3.0,NaN,NaN,NaN,3.5,6.25,8.00,NaN,NaN,NaN,16.50,13.55,NaN,18,Bac Giang,Mien Bac
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744391,744392,744392,4.6,4.50,6.0,3.75,3.00,3.25,NaN,NaN,NaN,NaN,11.35,10.85,NaN,15.1,14.35,52,Ba Ria Vung Tau,Mien Nam
744392,744393,744393,7.0,6.00,5.0,5.25,5.50,4.00,NaN,NaN,NaN,NaN,17.75,16.50,NaN,18,17.25,52,Ba Ria Vung Tau,Mien Nam
744393,744394,744394,5.2,3.50,4.0,6.25,5.50,2.25,NaN,NaN,NaN,NaN,16.95,12.95,NaN,12.7,15.45,52,Ba Ria Vung Tau,Mien Nam
744394,744395,744395,7.8,4.50,5.4,7.50,6.25,3.00,NaN,NaN,NaN,NaN,21.55,17.05,NaN,17.7,20.70,52,Ba Ria Vung Tau,Mien Nam
744395,744396,744396,5.8,3.50,3.0,6.25,4.75,3.25,NaN,NaN,NaN,NaN,16.80,13.80,NaN,12.3,15.05,52,Ba Ria Vung Tau,Mien Nam

In [2]:
df.isnull().sum()

0                   0
Unnamed: 1          0
SoBD                0
Toan             3372
Van             16087
Anh             84398
Ly             421043
Hoa            417415
Sinh           424791
Su             298278
Dia            311175
GDCD           365362
Unnamed: 10    744396
KhoiA          423164
KhoiB          424880
KhoiC          311791
KhoiD           88043
KhoiA1         436532
Ma Tinh             0
Ten Tinh            0
Vung mien           0
dtype: int64

In [3]:
file_to_process = ['Toan','Van', 'AnhVan','TenTinh']

In [10]:
#Thay thế giá trị thiếu của trường Toán bằng giá trị trung bình 
data = df.copy()
data.Toan.fillna(data.Toan.mean(), inplace=True)

In [11]:
#Thay thế giá trị thiếu của trường Toán bằng giá trị thường xuyên
data.Van.fillna(data.Van.mode()[0], inplace=True)

In [12]:
#Anh văn thay thế bằng giá trị thường xuyên theo trường tên tỉnh.
anh_mode = data.groupby('Ma Tinh')['Anh'].apply(lambda x:x.mode()[0]).to_dict()
data['Anh'] = data.apply(lambda x: anh_mode[x['Ma Tinh']] if pd.isnull(x['Anh']) else x['Anh'],axis =1)

In [13]:
data.isnull().sum()

0                   0
Unnamed: 1          0
SoBD                0
Toan                0
Van                 0
Anh                 0
Ly             421043
Hoa            417415
Sinh           424791
Su             298278
Dia            311175
GDCD           365362
Unnamed: 10    744396
KhoiA          423164
KhoiB          424880
KhoiC          311791
KhoiD           88043
KhoiA1         436532
Ma Tinh             0
Ten Tinh            0
Vung mien           0
dtype: int64

In [20]:
data

,0,Unnamed: 1,SoBD,Toan,Van,Anh,Ly,Hoa,Sinh,Su,...,GDCD,Unnamed: 10,KhoiA,KhoiB,KhoiC,KhoiD,KhoiA1,Ma Tinh,Ten Tinh,Vung mien
0,1,0.0,1,3.0,3.75,3.0,NaN,NaN,NaN,3.0,...,8.25,NaN,NaN,NaN,13.25,9.75,NaN,18,Bac Giang,Mien Bac
1,2,1.0,2,8.8,7.50,9.0,NaN,NaN,NaN,6.0,...,8.25,NaN,NaN,NaN,22.50,25.3,NaN,18,Bac Giang,Mien Bac
2,3,2.0,3,6.0,5.50,4.0,5.75,5.50,5.00,NaN,...,NaN,NaN,17.25,16.50,NaN,15.5,15.75,18,Bac Giang,Mien Bac
3,4,3.0,4,3.4,5.75,2.6,NaN,NaN,NaN,3.5,...,7.25,NaN,NaN,NaN,14.00,11.75,NaN,18,Bac Giang,Mien Bac
4,5,4.0,5,3.8,6.75,3.0,NaN,NaN,NaN,3.5,...,8.00,NaN,NaN,NaN,16.50,13.55,NaN,18,Bac Giang,Mien Bac
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744391,744392,744391.0,744392,4.6,4.50,6.0,3.75,3.00,3.25,NaN,...,NaN,NaN,11.35,10.85,NaN,15.1,14.35,52,Ba Ria Vung Tau,Mien Nam
744392,744393,744392.0,744393,7.0,6.00,5.0,5.25,5.50,4.00,NaN,...,NaN,NaN,17.75,16.50,NaN,18,17.25,52,Ba Ria Vung Tau,Mien Nam
744393,744394,744393.0,744394,5.2,3.50,4.0,6.25,5.50,2.25,NaN,...,NaN,NaN,16.95,12.95,NaN,12.7,15.45,52,Ba Ria Vung Tau,Mien Nam
744394,744395,744394.0,744395,7.8,4.50,5.4,7.50,6.25,3.00,NaN,...,NaN,NaN,21.55,17.05,NaN,17.7,20.70,52,Ba Ria Vung Tau,Mien Nam
744395,744396,744395.0,744396,5.8,3.50,3.0,6.25,4.75,3.25,NaN,...,NaN,NaN,16.80,13.80,NaN,12.3,15.05,52,Ba Ria Vung Tau,Mien Nam

In [25]:
#Các trường còn lại thay thế bằng giá trị “Khong thi”
data['Ly'] .fillna('Khong thi',inplace=True)
data['Hoa'] .fillna('Khong thi',inplace=True)
data['Sinh'] .fillna('Khong thi',inplace=True)
data['Su'] .fillna('Khong thi',inplace=True)
data['Dia'] .fillna('Khong thi',inplace=True)
data['GDCD'] .fillna('Khong thi',inplace=True)
data['KhoiA'] .fillna('Khong thi',inplace=True)
data['KhoiB'] .fillna('Khong thi',inplace=True)
data['KhoiC'] .fillna('Khong thi',inplace=True)
data['KhoiD'] .fillna('Khong thi',inplace=True)
data['KhoiA1'] .fillna('Khong thi',inplace=True)
data.isnull().sum()

0                   0
Unnamed: 1          0
SoBD                0
Toan                0
Van                 0
Anh                 0
Ly                  0
Hoa                 0
Sinh                0
Su                  0
Dia                 0
GDCD                0
Unnamed: 10    744396
KhoiA               0
KhoiB               0
KhoiC               0
KhoiD               0
KhoiA1              0
Ma Tinh             0
Ten Tinh            0
Vung mien           0
dtype: int64

In [28]:
#Tính toán tổng số giá trị thiếu của từng cột và tổng số dòng trong tệp dữ liệu:
data1= df.copy()
num_rows = len(data1)
null_values = data1.isnull().sum()

In [30]:
#Ví dụ xóa các cột dữ liệu có số lỗi >=50%
#Xóa những cột có số gá trị thiếu >=50%
columns_to_drop = []
for col in null_values.index:
    if null_values[col] / num_rows >= 0.5:
        columns_to_drop.append(col)
data1

,0,Unnamed: 1,SoBD,Toan,Van,Anh,Ly,Hoa,Sinh,Su,...,GDCD,Unnamed: 10,KhoiA,KhoiB,KhoiC,KhoiD,KhoiA1,Ma Tinh,Ten Tinh,Vung mien
0,1,0.0,1,3.0,3.75,3.0,NaN,NaN,NaN,3.0,...,8.25,NaN,NaN,NaN,13.25,9.75,NaN,18,Bac Giang,Mien Bac
1,2,1.0,2,8.8,7.50,9.0,NaN,NaN,NaN,6.0,...,8.25,NaN,NaN,NaN,22.50,25.3,NaN,18,Bac Giang,Mien Bac
2,3,2.0,3,6.0,5.50,4.0,5.75,5.50,5.00,NaN,...,NaN,NaN,17.25,16.50,NaN,15.5,15.75,18,Bac Giang,Mien Bac
3,4,3.0,4,3.4,5.75,2.6,NaN,NaN,NaN,3.5,...,7.25,NaN,NaN,NaN,14.00,11.75,NaN,18,Bac Giang,Mien Bac
4,5,4.0,5,3.8,6.75,3.0,NaN,NaN,NaN,3.5,...,8.00,NaN,NaN,NaN,16.50,13.55,NaN,18,Bac Giang,Mien Bac
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744391,744392,744391.0,744392,4.6,4.50,6.0,3.75,3.00,3.25,NaN,...,NaN,NaN,11.35,10.85,NaN,15.1,14.35,52,Ba Ria Vung Tau,Mien Nam
744392,744393,744392.0,744393,7.0,6.00,5.0,5.25,5.50,4.00,NaN,...,NaN,NaN,17.75,16.50,NaN,18,17.25,52,Ba Ria Vung Tau,Mien Nam
744393,744394,744393.0,744394,5.2,3.50,4.0,6.25,5.50,2.25,NaN,...,NaN,NaN,16.95,12.95,NaN,12.7,15.45,52,Ba Ria Vung Tau,Mien Nam
744394,744395,744394.0,744395,7.8,4.50,5.4,7.50,6.25,3.00,NaN,...,NaN,NaN,21.55,17.05,NaN,17.7,20.70,52,Ba Ria Vung Tau,Mien Nam
744395,744396,744395.0,744396,5.8,3.50,3.0,6.25,4.75,3.25,NaN,...,NaN,NaN,16.80,13.80,NaN,12.3,15.05,52,Ba Ria Vung Tau,Mien Nam

In [32]:
# Điền giá trị 0 cho những ô bị thiếu
data1.fillna(0, inplace=True)
data1

,0,Unnamed: 1,SoBD,Toan,Van,Anh,Ly,Hoa,Sinh,Su,...,GDCD,Unnamed: 10,KhoiA,KhoiB,KhoiC,KhoiD,KhoiA1,Ma Tinh,Ten Tinh,Vung mien
0,1,0.0,1,3.0,3.75,3.0,0.00,0.00,0.00,3.0,...,8.25,0.0,0.00,0.00,13.25,9.75,0.00,18,Bac Giang,Mien Bac
1,2,1.0,2,8.8,7.50,9.0,0.00,0.00,0.00,6.0,...,8.25,0.0,0.00,0.00,22.50,25.3,0.00,18,Bac Giang,Mien Bac
2,3,2.0,3,6.0,5.50,4.0,5.75,5.50,5.00,0.0,...,0.00,0.0,17.25,16.50,0.00,15.5,15.75,18,Bac Giang,Mien Bac
3,4,3.0,4,3.4,5.75,2.6,0.00,0.00,0.00,3.5,...,7.25,0.0,0.00,0.00,14.00,11.75,0.00,18,Bac Giang,Mien Bac
4,5,4.0,5,3.8,6.75,3.0,0.00,0.00,0.00,3.5,...,8.00,0.0,0.00,0.00,16.50,13.55,0.00,18,Bac Giang,Mien Bac
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744391,744392,744391.0,744392,4.6,4.50,6.0,3.75,3.00,3.25,0.0,...,0.00,0.0,11.35,10.85,0.00,15.1,14.35,52,Ba Ria Vung Tau,Mien Nam
744392,744393,744392.0,744393,7.0,6.00,5.0,5.25,5.50,4.00,0.0,...,0.00,0.0,17.75,16.50,0.00,18,17.25,52,Ba Ria Vung Tau,Mien Nam
744393,744394,744393.0,744394,5.2,3.50,4.0,6.25,5.50,2.25,0.0,...,0.00,0.0,16.95,12.95,0.00,12.7,15.45,52,Ba Ria Vung Tau,Mien Nam
744394,744395,744394.0,744395,7.8,4.50,5.4,7.50,6.25,3.00,0.0,...,0.00,0.0,21.55,17.05,0.00,17.7,20.70,52,Ba Ria Vung Tau,Mien Nam
744395,744396,744395.0,744396,5.8,3.50,3.0,6.25,4.75,3.25,0.0,...,0.00,0.0,16.80,13.80,0.00,12.3,15.05,52,Ba Ria Vung Tau,Mien Nam

In [34]:
data1.replace(0, pd.np.nan, inplace=True)
data1

C:\Users\Thuong\AppData\Local\Temp\ipykernel_14040\1496592305.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  data1.replace(0, pd.np.nan, inplace=True)

,0,Unnamed: 1,SoBD,Toan,Van,Anh,Ly,Hoa,Sinh,Su,...,GDCD,Unnamed: 10,KhoiA,KhoiB,KhoiC,KhoiD,KhoiA1,Ma Tinh,Ten Tinh,Vung mien
0,1,NaN,1,3.0,3.75,3.0,NaN,NaN,NaN,3.0,...,8.25,NaN,NaN,NaN,13.25,9.75,NaN,18,Bac Giang,Mien Bac
1,2,1.0,2,8.8,7.50,9.0,NaN,NaN,NaN,6.0,...,8.25,NaN,NaN,NaN,22.50,25.3,NaN,18,Bac Giang,Mien Bac
2,3,2.0,3,6.0,5.50,4.0,5.75,5.50,5.00,NaN,...,NaN,NaN,17.25,16.50,NaN,15.5,15.75,18,Bac Giang,Mien Bac
3,4,3.0,4,3.4,5.75,2.6,NaN,NaN,NaN,3.5,...,7.25,NaN,NaN,NaN,14.00,11.75,NaN,18,Bac Giang,Mien Bac
4,5,4.0,5,3.8,6.75,3.0,NaN,NaN,NaN,3.5,...,8.00,NaN,NaN,NaN,16.50,13.55,NaN,18,Bac Giang,Mien Bac
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744391,744392,744391.0,744392,4.6,4.50,6.0,3.75,3.00,3.25,NaN,...,NaN,NaN,11.35,10.85,NaN,15.1,14.35,52,Ba Ria Vung Tau,Mien Nam
744392,744393,744392.0,744393,7.0,6.00,5.0,5.25,5.50,4.00,NaN,...,NaN,NaN,17.75,16.50,NaN,18,17.25,52,Ba Ria Vung Tau,Mien Nam
744393,744394,744393.0,744394,5.2,3.50,4.0,6.25,5.50,2.25,NaN,...,NaN,NaN,16.95,12.95,NaN,12.7,15.45,52,Ba Ria Vung Tau,Mien Nam
744394,744395,744394.0,744395,7.8,4.50,5.4,7.50,6.25,3.00,NaN,...,NaN,NaN,21.55,17.05,NaN,17.7,20.70,52,Ba Ria Vung Tau,Mien Nam
744395,744396,744395.0,744396,5.8,3.50,3.0,6.25,4.75,3.25,NaN,...,NaN,NaN,16.80,13.80,NaN,12.3,15.05,52,Ba Ria Vung Tau,Mien Nam

In [38]:
for col in data1.columns:
    if col not in columns_to_drop:
        null_percentage = null_values[col] / num_rows
        if null_percentage <0.2:
            if data1[col].dtype == 'object':
                common_value = data1[col].mode()[0]
                data1[col].fillna(common_value, inplace=True)
            else:
                mean_value = data1[col].mean()
                data1[col].fillna(mean_value, inplace=True)
data1

,0,Unnamed: 1,SoBD,Toan,Van,Anh,Ly,Hoa,Sinh,Su,...,GDCD,Unnamed: 10,KhoiA,KhoiB,KhoiC,KhoiD,KhoiA1,Ma Tinh,Ten Tinh,Vung mien
0,1,372198.0,1,3.0,3.75,3.0,NaN,NaN,NaN,3.0,...,8.25,NaN,NaN,NaN,13.25,9.75,NaN,18,Bac Giang,Mien Bac
1,2,1.0,2,8.8,7.50,9.0,NaN,NaN,NaN,6.0,...,8.25,NaN,NaN,NaN,22.50,25.3,NaN,18,Bac Giang,Mien Bac
2,3,2.0,3,6.0,5.50,4.0,5.75,5.50,5.00,NaN,...,NaN,NaN,17.25,16.50,NaN,15.5,15.75,18,Bac Giang,Mien Bac
3,4,3.0,4,3.4,5.75,2.6,NaN,NaN,NaN,3.5,...,7.25,NaN,NaN,NaN,14.00,11.75,NaN,18,Bac Giang,Mien Bac
4,5,4.0,5,3.8,6.75,3.0,NaN,NaN,NaN,3.5,...,8.00,NaN,NaN,NaN,16.50,13.55,NaN,18,Bac Giang,Mien Bac
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744391,744392,744391.0,744392,4.6,4.50,6.0,3.75,3.00,3.25,NaN,...,NaN,NaN,11.35,10.85,NaN,15.1,14.35,52,Ba Ria Vung Tau,Mien Nam
744392,744393,744392.0,744393,7.0,6.00,5.0,5.25,5.50,4.00,NaN,...,NaN,NaN,17.75,16.50,NaN,18,17.25,52,Ba Ria Vung Tau,Mien Nam
744393,744394,744393.0,744394,5.2,3.50,4.0,6.25,5.50,2.25,NaN,...,NaN,NaN,16.95,12.95,NaN,12.7,15.45,52,Ba Ria Vung Tau,Mien Nam
744394,744395,744394.0,744395,7.8,4.50,5.4,7.50,6.25,3.00,NaN,...,NaN,NaN,21.55,17.05,NaN,17.7,20.70,52,Ba Ria Vung Tau,Mien Nam
744395,744396,744395.0,744396,5.8,3.50,3.0,6.25,4.75,3.25,NaN,...,NaN,NaN,16.80,13.80,NaN,12.3,15.05,52,Ba Ria Vung Tau,Mien Nam

In [13]:
# xóa những dòng có giá trị thiếu 
data3= data.copy()
data3.dropna(inplace=True)
data3.isnull().sum()

0              0.0
Unnamed: 1     0.0
SoBD           0.0
Toan           0.0
Van            0.0
Anh            0.0
Ly             0.0
Hoa            0.0
Sinh           0.0
Su             0.0
Dia            0.0
GDCD           0.0
Unnamed: 10    0.0
KhoiA          0.0
KhoiB          0.0
KhoiC          0.0
KhoiD          0.0
KhoiA1         0.0
Ma Tinh        0.0
Ten Tinh       0.0
Vung mien      0.0
dtype: float64

In [14]:
# chuẩn hóa theo zcore tính khoảng lệch cao nhất và thấp nhất so với tb bn độ lệch chuẩn
df_ly=data3['Ly']
z_score_ly=zscore(df_ly) #Tính z-score
z_score_ly #xuất ra màn hình

array([], dtype=float64)

In [15]:
# chuẩn hóa theo zcore tính khoảng lệch cao nhất và thấp nhất so với tb bn độ lệch chuẩn
df_toan=data3['Toan']
z_score_toan=zscore(df_toan) #Tính z-score
z_score_toan #xuất ra màn hình

array([], dtype=float64)

In [16]:
df_hoa=data3['Hoa']
z_score_hoa=zscore(df_hoa) #Tính z-score
z_score_hoa #xuất ra màn hình

array([], dtype=float64)

In [29]:
data1.to_csv('TotnghiepOK.csv')