In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy.stats import zscore
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

data = pd.read_csv('105OK.csv', usecols=range(10))
data.head(10)

,Unnamed: 0,Access,CT du lieu,CT may tinh,CNXHKH,Chuyen de,CS du lieu,Cong nghe NET,CNphan mem,Dai so so hoc
0,0,True,True,True,True,True,True,False,True,True
1,1,True,True,True,True,True,True,False,True,True
2,2,True,True,True,True,True,True,False,True,True
3,3,True,True,True,True,True,True,False,True,True
4,4,True,True,True,True,True,True,False,True,True
5,5,True,True,True,True,True,True,False,True,True
6,6,True,True,True,True,True,True,False,True,True
7,7,True,True,True,True,True,True,False,True,True
8,8,True,True,True,True,True,True,False,True,True
9,9,True,True,True,True,True,True,False,True,True

In [2]:

data.drop('Unnamed: 0',axis=1 ,inplace=True)
data

,Access,CT du lieu,CT may tinh,CNXHKH,Chuyen de,CS du lieu,Cong nghe NET,CNphan mem,Dai so so hoc
0,True,True,True,True,True,True,False,True,True
1,True,True,True,True,True,True,False,True,True
2,True,True,True,True,True,True,False,True,True
3,True,True,True,True,True,True,False,True,True
4,True,True,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...
94,False,True,True,True,True,True,True,True,True
95,False,True,True,True,True,True,True,True,True
96,False,True,True,True,True,True,True,True,True
97,False,True,True,True,True,True,True,True,True
98,False,False,False,False,False,False,False,False,False

In [3]:
#tìm tập mục phổ biến 
frequent_itemsets = apriori(data, min_support = 0.4,use_colnames = True )
frequent_itemsets

      support                                           itemsets
0    0.525253                                           (Access)
1    0.989899                                       (CT du lieu)
2    0.979798                                      (CT may tinh)
3    0.989899                                           (CNXHKH)
4    0.979798                                       (Chuyen de )
..        ...                                                ...
378  0.464646  (CS du lieu, Chuyen de , CT may tinh, Dai so s...
379  0.464646  (CS du lieu, Chuyen de , Dai so so hoc, Cong n...
380  0.464646  (CS du lieu, Chuyen de , CT may tinh, Dai so s...
381  0.515152  (CS du lieu, Chuyen de , CT may tinh, Dai so s...
382  0.464646  (CS du lieu, Chuyen de , CT may tinh, Dai so s...

[383 rows x 2 columns]

In [5]:
#Tìm luật kết hợp và lọc theo độ tin cậy
from mlxtend.frequent_patterns import association_rules
rules=association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Access),(CT du lieu),0.525253,0.989899,0.525253,1.000000,1.010204,0.005306,inf
1,(Access),(CT may tinh),0.525253,0.979798,0.515152,0.980769,1.000991,0.000510,1.050505
2,(Access),(CNXHKH),0.525253,0.989899,0.525253,1.000000,1.010204,0.005306,inf
3,(Access),(Chuyen de ),0.525253,0.979798,0.515152,0.980769,1.000991,0.000510,1.050505
4,(Access),(CS du lieu),0.525253,0.989899,0.525253,1.000000,1.010204,0.005306,inf
...,...,...,...,...,...,...,...,...,...
6045,"(Cong nghe NET , Dai so so hoc)","(CS du lieu, Chuyen de , CT may tinh, CNphan m...",0.464646,0.979798,0.464646,1.000000,1.020619,0.009387,inf
6046,"(Cong nghe NET , CNphan mem)","(CS du lieu, Chuyen de , CT may tinh, Dai so s...",0.464646,0.979798,0.464646,1.000000,1.020619,0.009387,inf
6047,"(CNXHKH, Cong nghe NET )","(CS du lieu, Chuyen de , CT may tinh, Dai so s...",0.464646,0.979798,0.464646,1.000000,1.020619,0.009387,inf
6048,"(CT du lieu, Cong nghe NET )","(CS du lieu, Chuyen de , CT may tinh, Dai so s...",0.464646,0.979798,0.464646,1.000000,1.020619,0.009387,inf
6049,(Cong nghe NET ),"(CS du lieu, Chuyen de , CT may tinh, Dai so s...",0.464646,0.979798,0.464646,1.000000,1.020619,0.009387,inf